version: '3.8'

services:
  web:
    container_name: web_application
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=coopersystem_db
      - POSTGRES_USER=coopersystemuser
      - POSTGRES_PASSWORD=coopersystemuser
    ports:
      - 5432:5432
    volumes:
     - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: